export default {
  info: 'district/info',
  banners: 'banners',
  merchantTypes: 'merchants/types',
  activities: 'activities',
  hotMerchants: 'merchants/hots',
  merchants: 'merchants',
  keywords: 'search_keywords',
  merchantDetail: 'merchant',
  fav: 'fav',
  favs: 'favs',
  points: 'points',
  coupons: 'coupons',
  receiveCoupon: 'coupon/receive',
  couponDetail: 'coupon/detail',
  couponShow: 'coupon/show',
  authorizations: 'etone/authorizations',
  autologin: 'openid/authorizations',
  userInfo: 'user',
  smsCode: 'verification_codes',
  bindMobile: 'user/bind',
  myCoupons: 'user/coupons',
  editUserInfo: 'user/edit',
  orders: 'user/orders'
}
